Repository dadoonet/elasticsearch-beyonder, pull requests merged in 2021-05, with the labels that each got.

#160 Add support for pipelines
  README.md
  src/main/java/fr/pilato/elasticsearch/tools/ElasticsearchBeyonder.java
  src/main/java/fr/pilato/elasticsearch/tools/SettingsFinder.java
  src/main/java/fr/pilato/elasticsearch/tools/index/IndexFinder.java
  src/main/java/fr/pilato/elasticsearch/tools/pipeline/PipelineElasticsearchUpdater.java
  src/main/java/fr/pilato/elasticsearch/tools/pipeline/PipelineFinder.java
  src/main/java/fr/pilato/elasticsearch/tools/pipeline/PipelineSettingsReader.java
  src/test/java/fr/pilato/elasticsearch/tools/BeyonderRestIT.java
  src/test/resources/models/pipeline/_pipeline/twitter_pipeline.json
Labels: new

#162 Add github actions
  .github/workflows/maven.yml
  .mergify.yml
  .travis.yml
  README.md
  deploy-settings.xml
  pom.xml
  src/test/resources/log4j2.xml
Labels: update

#161 Update to JDK14
  pom.xml
Labels: update

#163 Explain what the project is about
  README.md
Labels: doc

#164 Add support for update mapping
  .github/workflows/pr.yml
  README.md
  pom.xml
  src/main/java/fr/pilato/elasticsearch/tools/ElasticsearchBeyonder.java
  src/main/java/fr/pilato/elasticsearch/tools/ResourceList.java
  src/main/java/fr/pilato/elasticsearch/tools/SettingsFinder.java
  src/main/java/fr/pilato/elasticsearch/tools/index/IndexElasticsearchUpdater.java
  src/main/java/fr/pilato/elasticsearch/tools/index/IndexSettingsReader.java
  src/test/java/fr/pilato/elasticsearch/tools/AbstractBeyonderTest.java
  src/test/java/fr/pilato/elasticsearch/tools/BeyonderRestIT.java
  src/test/java/fr/pilato/elasticsearch/tools/BeyonderTransportIT.java
  src/test/java/fr/pilato/elasticsearch/tools/BeyonderUnitTest.java
  src/test/java/fr/pilato/elasticsearch/tools/JsonUtil.java
  src/test/resources/models/update-mapping/step1/twitter/_settings.json
  src/test/resources/models/update-mapping/step2/twitter/_update_mapping.json
  src/test/resources/transport/models/update-mapping/step1/twitter/_settings.json
  src/test/resources/transport/models/update-mapping/step2/twitter/_update_mapping.json
Labels: new
